import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Next Projects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <div className="bg-[#BFDBFE] py-1">
            <div className="w-10/12 mx-auto">
              <Navbar></Navbar>
            </div>
          </div>
          <div className="w-10/12 mx-auto min-h-screen">{children}</div>
          <div className="w-10/12 mx-auto">
            <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
